name: Makefile CI

on:
  # run manualy from the Actions tab
  workflow_dispatch:
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v5

    - name: install-python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
        cache: 'pip' # caching pip dependencies

    - name: pip-requirements
      run: pip install -r requirements.txt

    - name: npm-setup
      uses: actions/setup-node@v5
      with:
        node-version: 24

    - name: npm-install-setup
      uses: bahmutov/npm-install@v1
      with:
        working-directory: ./
    - name: build-docs
      run: ./build-docs-ci.sh

    - name: upload-artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: ./minio

  # Deployment job
  deploy:
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4